const JPEGSTRIPES_ACCESS_TOKEN = process.env.JPEGSTRIPES_ACCESS_TOKEN
const JPEGSTRIPES_REFRESH_TOKEN = process.env.JPEGSTRIPES_REFRESH_TOKEN

const SCLARF_ACCESS_TOKEN = process.env.SCLARF_ACCESS_TOKEN
const SCLARF_REFRESH_TOKEN = process.env.SCLARF_REFRESH_TOKEN

const E1ECTROMA_ACCESS_TOKEN = process.env.E1ECTROMA_ACCESS_TOKEN
const E1ECTROMA_REFRESH_TOKEN = process.env.E1ECTROMA_REFRESH_TOKEN

const DOMONINTENDO1_ACCESS_TOKEN = process.env.DOMONINTENDO1_ACCESS_TOKEN
const DOMONINTENDO1_REFRESH_TOKEN = process.env.DOMONINTENDO1_REFRESH_TOKEN

const PPUYYA_ACCESS_TOKEN = process.env.PPUYYA_ACCESS_TOKEN
const PPUYYA_REFRESH_TOKEN = process.env.PPUYYA_REFRESH_TOKEN

const ASTRAL_AN0MALY_ACCESS_TOKEN = process.env.ASTRAL_AN0MALY_ACCESS_TOKEN
const ASTRAL_AN0MALY_REFRESH_TOKEN = process.env.ASTRAL_AN0MALY_REFRESH_TOKEN

const DIRTYD0INKS_ACCESS_TOKEN = process.env.DIRTYD0INKS_ACCESS_TOKEN
const DIRTYD0INKS_REFRESH_TOKEN = process.env.DIRTYD0INKS_REFRESH_TOKEN

const ARTYINPINK_ACCESS_TOKEN = process.env.ARTYINPINK_ACCESS_TOKEN
const ARTYINPINK_REFRESH_TOKEN = process.env.ARTYINPINK_REFRESH_TOKEN

const THETARASTARK_ACCESS_TOKEN = process.env.THETARASTARK_ACCESS_TOKEN
const THETARASTARK_REFRESH_TOKEN = process.env.THETARASTARK_REFRESH_TOKEN

const SLEBTV_ACCESS_TOKEN = process.env.SLEBTV_ACCESS_TOKEN
const SLEBTV_REFRESH_TOKEN = process.env.SLEBTV_REFRESH_TOKEN

const CATJERKY_ACCESS_TOKEN = process.env.CATJERKY_ACCESS_TOKEN
const CATJERKY_REFRESH_TOKEN = process.env.CATJERKY_REFRESH_TOKEN

const SKITTLE108_ACCESS_TOKEN = process.env.SKITTLE108_ACCESS_TOKEN
const SKITTLE108_REFRESH_TOKEN = process.env.SKITTLE108_REFRESH_TOKEN

const COMMON_NICKNAMES = process.env.COMMON_NICKNAMES
const STARTING_LEMONS = process.env.STARTING_LEMONS
const HANGMAN_WINS = process.env.HANGMAN_WINS

const lemonyFresh = {
    jpegstripes: {
        id: 70624062,
        accessToken: JPEGSTRIPES_ACCESS_TOKEN,
        refreshToken: JPEGSTRIPES_REFRESH_TOKEN,
        subRaidMessage: `jpegstCoin jpegstJPEG jpegstCoin jpegstRAID jpegstCoin`,
        noSubRaidMessage: `HeyGuys TombRaid KAPOW JPEG RAID HeyGuys TombRaid KAPOW`,
        emotes: [
            `jpegstCoin`,
            `jpegstTimber`,
            `jpegstGeno`,
            `jpegstKylePls`,
            `jpegstBamJAM`,
            `jpegstCherry`,
            `jpegstKetchup`,
            `jpegstJulian`,
            `jpegstScoot`,
            `jpegstMitzi`,
            `jpegstApollo`,
            `jpegstHeyGuys`,
            `jpegstKylePog`,
            `jpegstSpamton`,
            `jpegstJPEG`,
            `jpegstRAID`,
            `jpegstYes`,
            `jpegstNo`,
            `jpegstOkay`,
            `jpegstChrome`,
            `jpegstBroken`,
            `jpegstSlay`,
            `jpegstTapeEnd`,
            `jpegstBlank`,
            `jpegstDog`,
            `jpegstBonk`,
            `jpegstMegamind`
        ],
        bttvEmotes: [
            `(ditto)`,
            `ApolloFly`,
            `BamJAM`,
            `bongoTap`,
            `BowserRAGE`,
            `catJAM`,
            `catLurk`,
            `CherryStomp`,
            `Clap`,
            `diddyJAM`,
            `HYPERCHOP`,
            `JulianGroove`,
            `KEKW`,
            `KetchupWave`,
            `KongDance`,
            `KyleFestivale`,
            `KyleSwish`,
            `LuckySway`,
            `Lurk`,
            `MallowDance`,
            `MarioDance`,
            `marioWave`,
            `MitziJump`,
            `modCheck`,
            `OMEGALUL`,
            `PartyKirby`,
            `PepeLaugh`,
            `popCat`,
            `raccPls`,
            `racJam`,
            `ratJAM`,
            `ScootPatch`,
            `VillagerTimber`,
            `WhitneyVibe`
        ],
        funnyCommands: [
            `!bestfood`,
            `!clappingmusicbyamericancomposerstevereich`,
            `!dog`,
            `!cat`,
            `!emoteshelp`,
            `!hamburger`,
            `!scrampt`,
            `!error`,
            `!spam`,
            `!spamhelp`,
            `!weed`,
            `!uwuhelp`,
            `!weedhelp`,
            `mmmhelp`
        ],
        redeems: [
            `!bigshot`,
            `!keygen`,
            `!spotion`,
            `!thebigone`,
            `!bowtie`,
            `!neo`,
            `!workout`,
            `!suscr1ber`,
            `!mario`,
            `!piano`,
            `!slip`,
            `!hamster`,
            `!alarm`,
            `!waste`,
            `!25k`,
            `!crabrave`,
            `!confusion`,
            `!soulja`,
            `!breakdance`,
            `!gigachad`,
            `!4d3d3d3`,
            `!feedcat`,
            `!polarbear`,
            `!graph`,
            `!checkmate`,
            `!shutup`,
            `!doggo`,
            `!marshmallows`,
            `!chocotaco`,
            `!rat`,
            `!hamburger`,
            `!chickendance`,
            `!come`,
            `!gauntlet`,
            `!princess`,
            `!rubbermaid`,
            `!peachsyrup`,
            `!skype`,
            `!ohhimark`,
            `!dripgoku`,
            `!gelatin`,
            `!cheesecake`,
            `!fancam`,
            `!nicecock`,
            `!lieblingsfach`,
            `!lavish`,
            `!shootme`,
            `!disk`,
            `!flagranterror`,
            `!technology`,
            `!bingchilling`,
            `!flagranterror`,
            `!litlizards`,
            `!raccoon`,
            `!gay`,
            `!turbomaxwaste`,
            `!where`,
            `!luigi`,
            `!water`,
            `!balloon`,
            `!hello`,
            `!litterbee`
        ],
    },
    sclarf: {
        id: 108504232,
        accessToken: SCLARF_ACCESS_TOKEN,
        refreshToken: SCLARF_REFRESH_TOKEN,
        subRaidMessage: `sclarfWave sclarfHearts sclarfYay SCLARF RAID sclarfYay sclarfHearts sclarfWave`,
        noSubRaidMessage: `HeyGuys CoolCat SCLARF RAID CoolCat HeyGuys`,
        emotes: [
            `sclarfRave`,
            `sclarfWobble`,
            `sclarfBark`,
            `sclarfSpin`,
            `sclarfPls`,
            `sclarfPopbonk`,
            `sclarfMad`,
            `sclarfHuh`,
            `sclarfHowdy`,
            `sclarfDog`,
            `sclarfAmazed`,
            `sclarfBlind`,
            `sclarfPalm`,
            `sclarfDead`,
            `sclarfSophisticated`,
            `sclarfLUL`,
            `sclarfHiss`,
            `sclarfHearts`,
            `sclarfDEEP`,
            `sclarfWave`,
            `sclarfSleep`,
            `sclarfD8`,
            `sclarfYay`,
            `sclarfChickenmoley`,
            `sclarfFlip`
        ],
        bttvEmotes: [
            `(ditto)`,
            `batJAM`,
            `BoneZone`,
            `bongoTap`,
            `BOOBA`,
            `catJAM`,
            `catKISS`,
            `Clap`,
            `Clueless`,
            `COPIUM`,
            `DIESOFGRINCH`,
            `DonoWall`,
            `EZ`,
            `GIGACHAD`,
            `gorgHAIP`,
            `hypeE`,
            `jesusBeBallin`,
            `KEKW`,
            `LICKA`,
            `LULW`,
            `Madge`,
            `MEOW`,
            `modCheck`,
            `monkaSTEER`,
            `monkaW`,
            `MorshuPls`,
            `NODDERS`,
            `NOOO`,
            `NOPERS`,
            `OMEGALUL`,
            `OOOO`,
            `peepoShy`
        ],
        funnyCommands: [
            `!accurateremember`,
            `!addcomb`,
            `!backfeet`,
            `!bonk2`,
            `!brainsnail`,
            `!brian`,
            `!c`,
            `!c8`,
            `!c10`,
            `!carl`,
            `!cc`,
            `!clown`,
            `!cock`,
            `!code`,
            `!cockin`,
            `!demonsouls`,
            `!dilf`,
            `!favfood`,
            `!flowage`,
            `!flow`,
            `!frog`,
            `!fuck`,
            `!hairclog`,
            `!iou`,
            `!lolmine`,
            `!laminar`,
            `!lemony_friend`,
            `!movie`,
            `!name`,
            `!newvid`,
            `!numbers`,
            `!passfuck`,
            `!ppuyya`,
            `!remember`,
            `!slay`,
            `!smash`,
            `!spam`,
            `!undertalebot`,
            `!vb`,
            `!what`,
            `!zelda`,
            `a`,
            `b`,
            `b2`,
            `b3`,
            `c`,
            `c-1`,
            `c1`,
            `c2`,
            `c3`,
            `c4`,
            `c5`,
            `c6`,
            `c7`,
            `c8`,
            `c9`,
            `c10`,
            `c11`,
            `c12`,
            `c13`,
            `c14`,
            `c15`,
            `c16`,
            `c17`,
            `c18`,
            `c19`,
            `c20`,
            `c21`,
            `c22`,
            `c23`,
            `c24`,
            `c69`,
            `c411`,
            `d`,
            `e`,
            `e18`,
            `f`,
            `g`,
            `h`,
            `j`,
            `l`,
            `listen`,
            `m`,
            `n`,
            `o`,
            `q`,
            `qq`,
            `s`,
            `t`,
            `v`,
            `w`,
            `x`,
            `x2`,
            `x3`,
            `y`,
            `z`
        ]
    },
    e1ectroma: {
        id: 467062147,
        accessToken: E1ECTROMA_ACCESS_TOKEN,
        refreshToken: E1ECTROMA_REFRESH_TOKEN,
        subRaidMessage: `e1ectr4Smile e1ectr4Pikadance ELECTROMA RAID e1ectr4Pikadance e1ectr4Smile`,
        noSubRaidMessage: `TombRaid ELECTROMA RAID TombRaid`,
        emotes: [
            `e1ectr4Lfg`,
            `e1ectr4Pikadance`,
            `e1ectr4Tromadance`,
            `e1ectr4Coop`,
            `e1ectr4Ocha`,
            `e1ectr4Hello`,
            `e1ectr4Hi`,
            `e1ectr4Bye`,
            `e1ectr4Laugh`,
            `e1ectr4Wazzah`,
            `e1ectr4Smile`,
            `e1ectr4Devil`,
            `e1ectr4Ram`,
            `e1ectr4Salute`,
            `e1ectr4Lemfresh`,
            `e1ectr4Moses`,
            `e1ectr4Josie`,
            `e1ectr4Malort`,
            `e1ectr4Heat`,
            `e1ectr4Umbreon`
        ],
        bttvEmotes: [
            `AlienPls`,
            `BlobDance`,
            `BoneZone`,
            `bongoTap`,
            `catJAM`,
            `chikaYo`,
            `Clap`,
            `dekuHYPE`,
            `KEKW`,
            `LULW`,
            `modCheck`,
            `OMEGALUL`,
            `PETTHEMODS`,
            `pikaO`,
            `PokeMon`,
            `PokemonTrainer`,
            `popCat`,
            `pressF`,
            `RareChar`,
            `ratJAM`,
            `ricardoFlick`,
            `sadCat`,
            `WeSmart`
        ],
        funnyCommands: [
            `!shit`,
            `!chumcocks`,
            `!unshit`,
            `!nomore`,
            `!kitty`,
            `!numbers`,
            `!encounter`,
            `!jewel`,
            `!fbi`,
            `!orbit`,
            `!krizpy`,
            `!glurk`,
            `!dadtime`,
            `!zeroth`
        ],
        redeems: [
            `!winner`,
            `!soda`,
            `!pipe`,
            `!nope`,
            `!nice`,
            `!n64`,
            `!bork`,
            `!maxwell`
        ],
        list: [
            `Quotes`,
            `"please god don't milk me" -trom 2025`,
            `"is latex cum?" -arty 2025`,
            `"that's a big shit and a big gig right there" -trom 2025`
        ]
    },
    domonintendo1: {
        id: 100792658,
        accessToken: DOMONINTENDO1_ACCESS_TOKEN,
        refreshToken: DOMONINTENDO1_REFRESH_TOKEN,
        subRaidMessage: `domoni6Mingo domoni6Sneeze domoni6Kek GET DOMONATED domoni6Kek domoni6Sneeze domoni6Mingo`,
        noSubRaidMessage: `PogChamp GET DOMONATED PogChamp`,
        emotes: [
            `domoni6Really`,
            `domoni6Bingo`,
            `domoni6ChefHey`,
            `domoni6MeincSus`,
            `domoni6Sneeze`,
            `domoni6Dum`,
            `domoni6Love`,
            `domoni6Boom`,
            `domoni6Kek`,
            `domoni6Mingo`,
            `domoni6Point`
        ],
        bttvEmotes: [
            `catJAM`,
            `ChipiChipi`,
            `coffinPLZ`,
            `COPIUM`,
            `Drake`,
            `gachiHYPER`,
            `GIGACHAD`,
            `HUHH`,
            `HYPERS`,
            `KEKW`,
            `marioD`,
            `marioFinger`,
            `Mariok`,
            `modCheck`,
            `monkaHmm`,
            `monkaTOS`,
            `monkaW`,
            `monkaX`,
            `NODDERS`,
            `OMEGALUL`,
            `PartyKirby`,
            `PauseChamp`,
            `peepoGiggles`,
            `peepoHappy`,
            `pepeD`,
            `pepeDS`,
            `Pepega`,
            `PepeLaugh`,
            `pepoG`,
            `pikaHi`,
            `POGGERS`,
            `ricardoFlick`,
            `sadCat`,
            `SunshineDance`,
            `tabsMario`,
            `tenseSmash`,
            `VegetaPain`,
            `weirdChamp`,
            `WeSmart`
        ],
        funnyCommands: [
            `!arena`,
            `!cdick`,
            `!code`,
            `!laurie`,
            `!jpef`,
            `!kitty`,
            `!pw`,
            `!remember`,
            `!skittle`,
            `!year`
        ],
        list: [
            `Games`,
            `Super Paper Mario`,
            `Okami`,
            `Captain Toad's Treasure Tracker`,
            `Animal Crossing`,
            `Far Cry Vengeance`,
            `Balatro`,
            `Subnautica`,
            `The Legend of Zelda: Skyward Sword`,
            `Resident Evil 7`,
            `The Legend of Zelda: Ocarina of Time`,
            `The Legend of Zelda: Majora's Mask`,
            `Dying Light`,
            `Dying Light 2`,
            `Dying Light 3`,
            `Kirby: Return to Dreamland`,
            `Graveyard Keeper`,
            `Stardew Valley`,
            `Baba Is You`,
            `Thank Goodness You're Here!`,
            `Factorio`,
            `Odama`
        ]
    },
    ppuyya: {
        id: 500904880,
        accessToken: PPUYYA_ACCESS_TOKEN,
        refreshToken: PPUYYA_REFRESH_TOKEN
    },
    astral_an0maly: {
        id: 144838577,
        emotes: [
            `astral332Pop`,
            `astral332Music`,
            `astral332Freddy`,
            `astral332Sherb`,
            `astral332Vibe`,
            `astral332Pophype`,
            `astral332Pophi`,
            `astral332Obs`,
            `astral332Lul`,
            `astral332Load`
        ],
        accessToken: ASTRAL_AN0MALY_ACCESS_TOKEN,
        refreshToken: ASTRAL_AN0MALY_REFRESH_TOKEN,
        subRaidMessage: `astral332Pophype astral332Pophi astral332Pop ASTRAL RAID astral332Pop astral332Pophi astral332Pophype`,
        noSubRaidMessage: `CorgiDerp ASTRAL RAID CorgiDerp`
    },
    dirtyd0inks: {
        id: 840745958,
        emotes: [`dirtyd182LOVE`],
        accessToken: DIRTYD0INKS_ACCESS_TOKEN,
        refreshToken: DIRTYD0INKS_REFRESH_TOKEN,
        noSubRaidMessage: `DinoDance GoldPLZ LETS GET DIRTY! GoldPLZ DinoDance`
    },
    artyinpink: {
        id: 558851202,
        emotes: [
            `cosyin1Hype`,
            `cosyin1Dance`,
            `cosyin1Love`,
            `cosyin1Crying`,
            `cosyin1Wave`,
            `cosyin1Cozy`,
            `cosyin1Evil`,
            `cosyin1Soft`
        ],
        accessToken: ARTYINPINK_ACCESS_TOKEN,
        refreshToken: ARTYINPINK_REFRESH_TOKEN,
        timers: { '!so': { cooldown: 4, listening: false } }
    },
    thetarastark: {
        id: 520011399,
        emotes: [
            `thetar42Andy`,
            `thetar42POG`,
            `thetar42GG`,
            `thetar42Fkickline`,
            `thetar42KeystonePride`,
            `thetar421st`,
            `thetar42Hoagie`,
            `thetar42Leave`,
            `thetar42Spin`,
            `thetar42Laser`,
            `thetar42BongoCatra`,
            `thetar42Pelican`,
            `thetar42Beanspelicans`,
            `thetar42Mdfly`,
            `thetar42Blep`,
            `thetar42Sad`,
            `thetar42Glare`,
            `thetar42KeystoneFlag`,
            `thetar42Cheer`
        ],
        bttvEmotes: [
            'Dance',
            'blobDance',
            'BoneZone',
            'hypeE',
            'bongoTap',
            'catDance',
            'pikaOMG',
            'CrabPls',
            'PartyKirby',
            'MYAAA',
            'KEKW',
            'OOOO',
            'ThisIsFine',
            'catJAM',
            'LETSGOOO',
            'ratJAM',
            'catKISS',
            'popCat',
            'NOOO',
            'monkaS',
            'Clap',
            'HAhaa',
            'ddHuh',
            'PParrot',
            'SNIFFA',
            'MEOW',
            'LETTHEMCOOK',
            'LETHERCOOK',
            'Sadge',
            'POGGERS',
            'LULW',
            'Blep',
            'FO1ST',
            '(ditto)',
            'dogeDance',
            'CrabRave',
            'Congratulations',
            'Prayge',
            'COPIUM',
            'VIBE',
            'OMEGALUL',
            'Pause',
            'COPIUM',
            'monkaSTEER',
            'monkaTOS',
            'Clueless'
        ],
        accessToken: THETARASTARK_ACCESS_TOKEN,
        refreshToken: THETARASTARK_REFRESH_TOKEN,
        timers: { '!so': { cooldown: 4, listening: false } }
    },
    slebtv: {
        id: 1013603562,
        accessToken: SLEBTV_ACCESS_TOKEN,
        refreshToken: SLEBTV_REFRESH_TOKEN
    }
}

const mods = {
    catjerky: {
        id: 61517604,
        accessToken: CATJERKY_ACCESS_TOKEN,
        refreshToken: CATJERKY_REFRESH_TOKEN
    },
    skittle108: {
        id: 208969030,
        accessToken: SKITTLE108_ACCESS_TOKEN,
        refreshToken: SKITTLE108_REFRESH_TOKEN
    }
}

const users = {}

const commonNicknames = {}
for (let arr = COMMON_NICKNAMES.split(`,`), i = 0; i < arr.length; i++) { if (i % 2 === 0) { commonNicknames[arr[i]] = arr[i + 1] } }

const startingLemons = {}
for (let arr = STARTING_LEMONS.split(`,`), i = 0; i < arr.length; i++) { if (i % 2 === 0) { startingLemons[arr[i]] = Number(arr[i + 1]) } }

const hangmanWins = {}
for (let arr = HANGMAN_WINS.split(`,`), i = 0; i < arr.length; i++) { if (i % 2 === 0) { hangmanWins[arr[i]] = Number(arr[i + 1]) } }

const knownTags = {}

const tempCmds = {}

module.exports = {
    lemonyFresh,
    mods,
    users,
    commonNicknames,
    startingLemons,
    hangmanWins,
    knownTags,
    tempCmds
}
