const BOT_ACCESS_TOKEN = process.env.BOT_ACCESS_TOKEN
const JPEGSTRIPES_ACCESS_TOKEN = process.env.JPEGSTRIPES_ACCESS_TOKEN
const JPEGSTRIPES_REFRESH_TOKEN = process.env.JPEGSTRIPES_REFRESH_TOKEN
const SCLARF_ACCESS_TOKEN = process.env.SCLARF_ACCESS_TOKEN
const SCLARF_REFRESH_TOKEN = process.env.SCLARF_REFRESH_TOKEN
const E1ECTROMA_ACCESS_TOKEN = process.env.E1ECTROMA_ACCESS_TOKEN
const E1ECTROMA_REFRESH_TOKEN = process.env.E1ECTROMA_REFRESH_TOKEN
const DOMONINTENDO1_ACCESS_TOKEN = process.env.DOMONINTENDO1_ACCESS_TOKEN
const DOMONINTENDO1_REFRESH_TOKEN = process.env.DOMONINTENDO1_REFRESH_TOKEN
const PPUYYA_ACCESS_TOKEN = process.env.PPUYYA_ACCESS_TOKEN
const PPUYYA_REFRESH_TOKEN = process.env.PPUYYA_REFRESH_TOKEN

const lemonyFresh = {
    channels: [
        `#jpegstripes`,
        `#sclarf`,
        `#e1ectroma`,
        `#domonintendo1`,
        `#ppuyya`
    ],
    botAccessToken: BOT_ACCESS_TOKEN,
    jpegstripes: {
        id: 70624062,
        accessToken: JPEGSTRIPES_ACCESS_TOKEN,
        refreshToken: JPEGSTRIPES_REFRESH_TOKEN,
        funTimer: 0,
        funTimerGuesser: ``,
        pollId: ``,
        subRaidMessage: `jpegstCoin jpegstJPEG jpegstCoin jpegstRAID jpegstCoin`,
        noSubRaidMessage: `HeyGuys TombRaid KAPOW JPEG RAID HeyGuys TombRaid KAPOW`,
        emotes: [
            `jpegstCoin`,
            `jpegstTimber`,
            `jpegstGeno`,
            `jpegstKylePls`,
            `jpegstBamJAM`,
            `jpegstLucky`,
            `jpegstKetchup`,
            `jpegstJulian`,
            `jpegstScoot`,
            `jpegstWhitney`,
            `jpegstApollo`,
            `jpegstHeyGuys`,
            `jpegstKylePog`,
            `jpegstSpamton`,
            `jpegstJPEG`,
            `jpegstRAID`,
            `jpegstYes`,
            `jpegstNo`,
            `jpegstOkay`,
            `jpegstChrome`,
            `jpegstBroken`,
            `jpegstSlay`,
            `jpegstTapeEnd`,
            `jpegstBlank`,
            `jpegstDog`,
            `jpegstBonk`,
            `jpegstMegamind`
        ],
        bttvEmotes: [
            `(ditto)`,
            `ApolloFly`,
            `BamJAM`,
            `bongoTap`,
            `BowserRAGE`,
            `catJAM`,
            `CherryStomp`,
            `Clap`,
            `diddyJAM`,
            `HYPERCHOP`,
            `JulianGroove`,
            `KEKW`,
            `KetchupWave`,
            `KongDance`,
            `KyleFestivale`,
            `KyleSwish`,
            `LuckySway`,
            `MitziJump`,
            `modCheck`,
            `OMEGALUL`,
            `PartyKirby`,
            `PepeLaugh`,
            `popCat`,
            `raccPls`,
            `racJam`,
            `ratJAM`,
            `ScootPatch`,
            `VillagerTimber`,
            `WhitneyVibe`
        ],
        redeems: [
            `!bigshot`,
            `!keygen`,
            `!spotion`,
            `!thebigone`,
            `!bowtie`,
            `!neo`,
            `!workout`,
            `!suscr1ber`,
            `!mario`,
            `!piano`,
            `!slip`,
            `!hamster`,
            `!alarm`,
            `!waste`,
            `!25k`,
            `!crabrave`,
            `!confusion`,
            `!soulja`,
            `!breakdance`,
            `!gigachad`,
            `!4d3d3d3`,
            `!feedcat`,
            `!polarbear`,
            `!graph`,
            `!checkmate`,
            `!shutup`,
            `!doggo`,
            `!marshmallows`,
            `!chocotaco`,
            `!rat`,
            `!hamburger`,
            `!chickendance`,
            `!come`,
            `!gauntlet`,
            `!princess`,
            `!rubbermaid`,
            `!peachsyrup`,
            `!skype`,
            `!ohhimark`,
            `!dripgoku`,
            `!gelatin`,
            `!cheesecake`,
            `!fancam`,
            `!nicecock`,
            `!lieblingsfach`,
            `!lavish`,
            `!shootme`,
            `!disk`,
            `!flagranterror`,
            `!technology`,
            `!bingchilling`,
            `!flagranterror`,
            `!litlizards`,
            `!raccoon`,
            `!gay`,
            `!turbomaxwaste`,
            `!where`,
            `!luigi`
        ],
        hangman: {
            listening: false,
            signup: false,
            answer: ``,
            spaces: [],
            players: [],
            guessedLetters: [],
            chances: 6,
            currentPlayer: 0
        },
        riddle: {
            question: ``,
            answer: ``
        }
    },
    sclarf: {
        id: 108504232,
        accessToken: SCLARF_ACCESS_TOKEN,
        refreshToken: SCLARF_REFRESH_TOKEN,
        funTimer: 0,
        funTimerGuesser: ``,
        pollId: ``,
        subRaidMessage: `sclarfWave sclarfHearts sclarfYay SCLARF RAID sclarfYay sclarfHearts sclarfWave`,
        noSubRaidMessage: `HeyGuys HahaSweat SCLARF RAID HahaSweat HeyGuys`,
        emotes: [
            `sclarfRave`,
            `sclarfWobble`,
            `sclarfBark`,
            `sclarfSpin`,
            `sclarfPls`,
            `sclarfPopbonk`,
            `sclarfMad`,
            `sclarfHuh`,
            `sclarfHowdy`,
            `sclarfDog`,
            `sclarfAmazed`,
            `sclarfBlind`,
            `sclarfPalm`,
            `sclarfDead`,
            `sclarfSophisticated`,
            `sclarfLUL`,
            `sclarfHiss`,
            `sclarfHearts`,
            `sclarfDEEP`,
            `sclarfWave`,
            `sclarfSleep`,
            `sclarfD8`,
            `sclarfYay`,
            `sclarfChickenmoley`
        ],
        bttvEmotes: [
            `(ditto)`,
            `batJAM`,
            `BoneZone`,
            `bongoTap`,
            `BOOBA`,
            `catJAM`,
            `catKISS`,
            `Clap`,
            `Clueless`,
            `COPIUM`,
            `DIESOFGRINCH`,
            `DonoWall`,
            `EZ`,
            `GIGACHAD`,
            `gorgHAIP`,
            `hypeE`,
            `jesusBeBallin`,
            `KEKW`,
            `LICKA`,
            `LULW`,
            `Madge`,
            `MEOW`,
            `modCheck`,
            `monkaSTEER`,
            `monkaW`,
            `MorshuPls`,
            `NODDERS`,
            `NOOO`,
            `NOPERS`,
            `OMEGALUL`,
            `OOOO`,
            `peepoShy`
        ],
        redeems: [],
        hangman: {
            listening: false,
            signup: false,
            answer: ``,
            spaces: [],
            players: [],
            guessedLetters: [],
            chances: 6,
            currentPlayer: 0
        },
        riddle: {
            question: ``,
            answer: ``
        }
    },
    e1ectroma: {
        id: 467062147,
        accessToken: E1ECTROMA_ACCESS_TOKEN,
        refreshToken: E1ECTROMA_REFRESH_TOKEN,
        funTimer: 0,
        funTimerGuesser: ``,
        pollId: ``,
        subRaidMessage: `e1ectr4Smile e1ectr4Pikadance ELECTROMA RAID e1ectr4Pikadance e1ectr4Smile`,
        noSubRaidMessage: `TombRaid ELECTROMA RAID TombRaid `,
        emotes: [
            `e1ectr4Lfg`,
            `e1ectr4Pikadance`,
            `e1ectr4Tromadance`,
            `e1ectr4Coop`,
            `e1ectr4Ocha`,
            `e1ectr4Hello`,
            `e1ectr4Hi`,
            `e1ectr4Bye`,
            `e1ectr4Laugh`,
            `e1ectr4Wazzah`,
            `e1ectr4Smile`,
            `e1ectr4Devil`,
            `e1ectr4Ram`,
            `e1ectr4Salute`,
            `e1ectr4Lemfresh`,
            `e1ectr4Moses`,
            `e1ectr4Josie`,
            `e1ectr4Malort`,
            `e1ectr4Heat`,
            `e1ectr4Umbreon`
        ],
        bttvEmotes: [
            `AlienPls`,
            `BlobDance`,
            `BoneZone`,
            `bongoTap`,
            `catJAM`,
            `chikaYo`,
            `Clap`,
            `dekuHYPE`,
            `KEKW`,
            `LULW`,
            `modCheck`,
            `OMEGALUL`,
            `PETTHEMODS`,
            `pikaO`,
            `PokeMon`,
            `PokemonTrainer`,
            `popCat`,
            `pressF`,
            `RareChar`,
            `ratJAM`,
            `ricardoFlick`,
            `sadCat`,
            `WeSmart`
        ],
        redeems: [
            `!winner`,
            `!soda`,
            `!pipe`,
            `!nope`,
            `!nice`,
            `!n64`,
            `!bork`,
            `!maxwell`
        ],
        hangman: {
            listening: false,
            signup: false,
            answer: ``,
            spaces: [],
            players: [],
            guessedLetters: [],
            chances: 6,
            currentPlayer: 0
        },
        riddle: {
            question: ``,
            answer: ``
        }
    },
    domonintendo1: {
        id: 100792658,
        accessToken: DOMONINTENDO1_ACCESS_TOKEN,
        refreshToken: DOMONINTENDO1_REFRESH_TOKEN,
        funTimer: 0,
        funTimerGuesser: ``,
        pollId: ``,
        subRaidMessage: `domoni6ChefHey HEY, DOMOSAPIENS HAVE ARRIVED domoni6ChefHey`,
        noSubRaidMessage: `PogChamp HEY, DOMOSAPIENS HAVE ARRIVED PogChamp`,
        emotes: [
            `domoni6Really`,
            `domoni6Bingo`,
            `domoni6ChefHey`,
            `domoni6MeincSus`,
            `domoni6Sneeze`,
            `domoni6Dum`,
            `domoni6Love`,
            `domoni6Boom`,
            `domoni6Kek`,
            `domoni6Mingo`
        ],
        bttvEmotes: [
            `catJAM`,
            `ChristmasCatJam`,
            `ChristmasDonk1`,
            `ChristmasDonk2`,
            `ChristmasDonk3`,
            `ChristmasDonk4`,
            `ChristmasPartyKirby`,
            `coffinPLZ`,
            `Drake`,
            `gachiHYPER`,
            `GIGACHAD`,
            `HUHH`,
            `HYPERS`,
            `KEKW`,
            `modCheck`,
            `monkaHmm`,
            `monkaTOS`,
            `monkaW`,
            `monkaX`,
            `NODDERS`,
            `OMEGALUL`,
            `PauseChamp`,
            `peepoGiggles`,
            `pepeD`,
            `pepeDS`,
            `Pepega`,
            `PepeLaugh`,
            `pepeSanta`,
            `PepoChristmas`,
            `pepoG`,
            `POGGERS`,
            `ricardoFlick`,
            `sadCat`,
            `tenseSmash`,
            `weirdChamp`,
            `WeSmart`
        ],
        redeems: [],
        hangman: {
            listening: false,
            signup: false,
            answer: ``,
            spaces: [],
            players: [],
            guessedLetters: [],
            chances: 6,
            currentPlayer: 0
        },
        riddle: {
            question: ``,
            answer: ``
        }
    },
    ppuyya: {
        id: 500904880,
        accessToken: PPUYYA_ACCESS_TOKEN,
        refreshToken: PPUYYA_REFRESH_TOKEN,
        funTimer: 0,
        funTimerGuesser: ``,
        pollId: ``,
        subRaidMessage: ``,
        noSubRaidMessage: ``,
        emotes: [],
        bttvEmotes: [],
        redeems: [],
        hangman: {
            listening: false,
            signup: false,
            answer: ``,
            spaces: [],
            players: [],
            guessedLetters: [],
            chances: 6,
            currentPlayer: 0
        },
        riddle: {
            question: ``,
            answer: ``
        }
    }
}

const mods = {}

const users = {}

const tempCmds = {}

module.exports = {
    lemonyFresh,
    mods,
    users,
    tempCmds
}
