const { settings } = require(`../config`)
const { getContextEmote, logMessage } = require(`../utils`)

const validTimeZones = {
    [/^(africa\/)?abidjan$/i]: `Africa/Abidjan`,
    [/^(africa\/)?algiers$/i]: `Africa/Algiers`,
    [/^(africa\/)?bissau$/i]: `Africa/Bissau`,
    [/^(africa\/)?cairo$/i]: `Africa/Cairo`,
    [/^(africa\/)?casablanca$/i]: `Africa/Casablanca`,
    [/^(africa\/)?ceuta$/i]: `Africa/Ceuta`,
    [/^(africa\/)?el(_| )?aaiun$/i]: `Africa/El_Aaiun`,
    [/^(africa\/)?johannesburg$/i]: `Africa/Johannesburg`,
    [/^(africa\/)?juba$/i]: `Africa/Juba`,
    [/^(africa\/)?khartoum$/i]: `Africa/Khartoum`,
    [/^(africa\/)?lagos$/i]: `Africa/Lagos`,
    [/^(africa\/)?maputo$/i]: `Africa/Maputo`,
    [/^(africa\/)?monrovia$/i]: `Africa/Monrovia`,
    [/^(africa\/)?nairobi$/i]: `Africa/Nairobi`,
    [/^(africa\/)?ndjamena$/i]: `Africa/Ndjamena`,
    [/^(africa\/)?sao(_| )?tome$/i]: `Africa/Sao_Tome`,
    [/^(africa\/)?tripoli$/i]: `Africa/Tripoli`,
    [/^(africa\/)?tunis$/i]: `Africa/Tunis`,
    [/^(africa\/)?windhoek$/i]: `Africa/Windhoek`,
    [/^(africa\/)?asmera$/i]: `Africa/Nairobi`,
    [/^(africa\/)?blantyre$/i]: `Africa/Maputo`,
    [/^(africa\/)?bujumbura$/i]: `Africa/Maputo`,
    [/^(africa\/)?gaborone$/i]: `Africa/Maputo`,
    [/^(africa\/)?harare$/i]: `Africa/Maputo`,
    [/^(africa\/)?kigali$/i]: `Africa/Maputo`,
    [/^(africa\/)?lubumbashi$/i]: `Africa/Maputo`,
    [/^(africa\/)?lusaka$/i]: `Africa/Maputo`,
    [/^(africa\/)?addis(_| )?ababa$/i]: `Africa/Nairobi`,
    [/^(africa\/)?asmara$/i]: `Africa/Nairobi`,
    [/^(africa\/)?dar(_| )?es(_| )?salaam$/i]: `Africa/Nairobi`,
    [/^(africa\/)?djibouti$/i]: `Africa/Nairobi`,
    [/^(africa\/)?kampala$/i]: `Africa/Nairobi`,
    [/^(africa\/)?mogadishu$/i]: `Africa/Nairobi`,
    [/^(africa\/)?accra$/i]: `Africa/Abidjan`,
    [/^(africa\/)?bamako$/i]: `Africa/Abidjan`,
    [/^(africa\/)?banjul$/i]: `Africa/Abidjan`,
    [/^(africa\/)?conakry$/i]: `Africa/Abidjan`,
    [/^(africa\/)?dakar$/i]: `Africa/Abidjan`,
    [/^(africa\/)?freetown$/i]: `Africa/Abidjan`,
    [/^(africa\/)?lome$/i]: `Africa/Abidjan`,
    [/^(africa\/)?nouakchott$/i]: `Africa/Abidjan`,
    [/^(africa\/)?ouagadougou$/i]: `Africa/Abidjan`,
    [/^(africa\/)?timbuktu$/i]: `Africa/Abidjan`,
    [/^(africa\/)?maseru$/i]: `Africa/Johannesburg`,
    [/^(africa\/)?mbabane$/i]: `Africa/Johannesburg`,
    [/^(africa\/)?bangui$/i]: `Africa/Lagos`,
    [/^(africa\/)?brazzaville$/i]: `Africa/Lagos`,
    [/^(africa\/)?douala$/i]: `Africa/Lagos`,
    [/^(africa\/)?kinshasa$/i]: `Africa/Lagos`,
    [/^(africa\/)?libreville$/i]: `Africa/Lagos`,
    [/^(africa\/)?luanda$/i]: `Africa/Lagos`,
    [/^(africa\/)?malabo$/i]: `Africa/Lagos`,
    [/^(africa\/)?niamey$/i]: `Africa/Lagos`,
    [/^(africa\/)?porto-?novo$/i]: `Africa/Lagos`,
    [/^(america\/)?adak$/i]: `America/Adak`,
    [/^(america\/)?anchorage$/i]: `America/Anchorage`,
    [/^(america\/)?araguaina$/i]: `America/Araguaina`,
    [/^(america\/)?(argentina\/)?buenos(_| )?aires$/i]: `America/Argentina/Buenos_Aires`,
    [/^(america\/)?(argentina\/)?catamarca$/i]: `America/Argentina/Catamarca`,
    [/^(america\/)?(argentina\/)?cordoba$/i]: `America/Argentina/Cordoba`,
    [/^(america\/)?(argentina\/)?jujuy$/i]: `America/Argentina/Jujuy`,
    [/^(america\/)?(argentina\/)?la(_| )?rioja$/i]: `America/Argentina/La_Rioja`,
    [/^(america\/)?(argentina\/)?mendoza$/i]: `America/Argentina/Mendoza`,
    [/^(america\/)?(argentina\/)?rio(_| )?gallegos$/i]: `America/Argentina/Rio_Gallegos`,
    [/^(america\/)?(argentina\/)?salta$/i]: `America/Argentina/Salta`,
    [/^(america\/)?(argentina\/)?san(_| )?juan$/i]: `America/Argentina/San_Juan`,
    [/^(america\/)?(argentina\/)?san(_| )?luis$/i]: `America/Argentina/San_Luis`,
    [/^(america\/)?(argentina\/)?tucuman$/i]: `America/Argentina/Tucuman`,
    [/^(america\/)?(argentina\/)?ushuaia$/i]: `America/Argentina/Ushuaia`,
    [/^(america\/)?asuncion$/i]: `America/Asuncion`,
    [/^(america\/)?bahia$/i]: `America/Bahia`,
    [/^(america\/)?bahia(_| )?banderas$/i]: `America/Bahia_Banderas`,
    [/^(america\/)?barbados$/i]: `America/Barbados`,
    [/^(america\/)?belem$/i]: `America/Belem`,
    [/^(america\/)?belize$/i]: `America/Belize`,
    [/^(america\/)?boa(_| )?vista$/i]: `America/Boa_Vista`,
    [/^(america\/)?bogota$/i]: `America/Bogota`,
    [/^(america\/)?boise$/i]: `America/Boise`,
    [/^(america\/)?cambridge(_| )?bay$/i]: `America/Cambridge_Bay`,
    [/^(america\/)?campo(_| )?grande$/i]: `America/Campo_Grande`,
    [/^(america\/)?cancun$/i]: `America/Cancun`,
    [/^(america\/)?caracas$/i]: `America/Caracas`,
    [/^(america\/)?cayenne$/i]: `America/Cayenne`,
    [/^(america\/)?chicago$/i]: `America/Chicago`,
    [/^(america\/)?chihuahua$/i]: `America/Chihuahua`,
    [/^(america\/)?costa(_| )?rica$/i]: `America/Costa_Rica`,
    [/^(america\/)?cuiaba$/i]: `America/Cuiaba`,
    [/^(america\/)?danmarkshavn$/i]: `America/Danmarkshavn`,
    [/^(america\/)?dawson$/i]: `America/Dawson`,
    [/^(america\/)?dawson(_| )?creek$/i]: `America/Dawson_Creek`,
    [/^(america\/)?denver$/i]: `America/Denver`,
    [/^(america\/)?detroit$/i]: `America/Detroit`,
    [/^(america\/)?edmonton$/i]: `America/Edmonton`,
    [/^(america\/)?eirunepe$/i]: `America/Eirunepe`,
    [/^(america\/)?el(_| )?salvador$/i]: `America/El_Salvador`,
    [/^(america\/)?fort(_| )?nelson$/i]: `America/Fort_Nelson`,
    [/^(america\/)?fortaleza$/i]: `America/Fortaleza`,
    [/^(america\/)?glace(_| )?bay$/i]: `America/Glace_Bay`,
    [/^(america\/)?goose(_| )?bay$/i]: `America/Goose_Bay`,
    [/^(america\/)?grand(_| )?turk$/i]: `America/Grand_Turk`,
    [/^(america\/)?guatemala$/i]: `America/Guatemala`,
    [/^(america\/)?guayaquil$/i]: `America/Guayaquil`,
    [/^(america\/)?guyana$/i]: `America/Guyana`,
    [/^(america\/)?halifax$/i]: `America/Halifax`,
    [/^(america\/)?havana$/i]: `America/Havana`,
    [/^(america\/)?hermosillo$/i]: `America/Hermosillo`,
    [/^(america\/)?(indiana\/)?indianapolis$/i]: `America/Indiana/Indianapolis`,
    [/^(america\/)?(indiana\/)?knox$/i]: `America/Indiana/Knox`,
    [/^(america\/)?(indiana\/)?marengo$/i]: `America/Indiana/Marengo`,
    [/^(america\/)?(indiana\/)?petersburg$/i]: `America/Indiana/Petersburg`,
    [/^(america\/)?(indiana\/)?tell(_| )?city$/i]: `America/Indiana/Tell_City`,
    [/^(america\/)?(indiana\/)?vevay$/i]: `America/Indiana/Vevay`,
    [/^(america\/)?(indiana\/)?vincennes$/i]: `America/Indiana/Vincennes`,
    [/^(america\/)?(indiana\/)?winamac$/i]: `America/Indiana/Winamac`,
    [/^(america\/)?inuvik$/i]: `America/Inuvik`,
    [/^(america\/)?iqaluit$/i]: `America/Iqaluit`,
    [/^(america\/)?jamaica$/i]: `America/Jamaica`,
    [/^(america\/)?juneau$/i]: `America/Juneau`,
    [/^(america\/)?(kentucky\/)?louisville$/i]: `America/Kentucky/Louisville`,
    [/^(america\/)?(kentucky\/)?monticello$/i]: `America/Kentucky/Monticello`,
    [/^(america\/)?la(_| )?paz$/i]: `America/La_Paz`,
    [/^(america\/)?lima$/i]: `America/Lima`,
    [/^(america\/)?los(_| )?angeles$/i]: `America/Los_Angeles`,
    [/^(america\/)?maceio$/i]: `America/Maceio`,
    [/^(america\/)?managua$/i]: `America/Managua`,
    [/^(america\/)?manaus$/i]: `America/Manaus`,
    [/^(america\/)?martinique$/i]: `America/Martinique`,
    [/^(america\/)?matamoros$/i]: `America/Matamoros`,
    [/^(america\/)?mazatlan$/i]: `America/Mazatlan`,
    [/^(america\/)?menominee$/i]: `America/Menominee`,
    [/^(america\/)?merida$/i]: `America/Merida`,
    [/^(america\/)?metlakatla$/i]: `America/Metlakatla`,
    [/^(america\/)?mexico(_| )?city$/i]: `America/Mexico_City`,
    [/^(america\/)?miquelon$/i]: `America/Miquelon`,
    [/^(america\/)?moncton$/i]: `America/Moncton`,
    [/^(america\/)?monterrey$/i]: `America/Monterrey`,
    [/^(america\/)?montevideo$/i]: `America/Montevideo`,
    [/^(america\/)?new(_| )?york$/i]: `America/New_York`,
    [/^(america\/)?nome$/i]: `America/Nome`,
    [/^(america\/)?noronha$/i]: `America/Noronha`,
    [/^(america\/)?(north(_| )?dakota\/)?beulah$/i]: `America/North_Dakota/Beulah`,
    [/^(america\/)?(north(_| )?dakota\/)?center$/i]: `America/North_Dakota/Center`,
    [/^(america\/)?(north(_| )?dakota\/)?new(_| )?salem$/i]: `America/North_Dakota/New_Salem`,
    [/^(america\/)?nuuk$/i]: `America/Nuuk`,
    [/^(america\/)?ojinaga$/i]: `America/Ojinaga`,
    [/^(america\/)?panama$/i]: `America/Panama`,
    [/^(america\/)?paramaribo$/i]: `America/Paramaribo`,
    [/^(america\/)?phoenix$/i]: `America/Phoenix`,
    [/^(america\/)?port-?au-?prince$/i]: `America/Port-au-Prince`,
    [/^(america\/)?porto(_| )?velho$/i]: `America/Porto_Velho`,
    [/^(america\/)?puerto(_| )?rico$/i]: `America/Puerto_Rico`,
    [/^(america\/)?punta(_| )?arenas$/i]: `America/Punta_Arenas`,
    [/^(america\/)?rankin(_| )?inlet$/i]: `America/Rankin_Inlet`,
    [/^(america\/)?recife$/i]: `America/Recife`,
    [/^(america\/)?regina$/i]: `America/Regina`,
    [/^(america\/)?resolute$/i]: `America/Resolute`,
    [/^(america\/)?rio(_| )?branco$/i]: `America/Rio_Branco`,
    [/^(america\/)?santarem$/i]: `America/Santarem`,
    [/^(america\/)?santiago$/i]: `America/Santiago`,
    [/^(america\/)?santo(_| )?domingo$/i]: `America/Santo_Domingo`,
    [/^(america\/)?sao(_| )?paulo$/i]: `America/Sao_Paulo`,
    [/^(america\/)?scoresbysund$/i]: `America/Scoresbysund`,
    [/^(america\/)?sitka$/i]: `America/Sitka`,
    [/^(america\/)?st(_| )?johns$/i]: `America/St_Johns`,
    [/^(america\/)?swift(_| )?current$/i]: `America/Swift_Current`,
    [/^(america\/)?tegucigalpa$/i]: `America/Tegucigalpa`,
    [/^(america\/)?thule$/i]: `America/Thule`,
    [/^(america\/)?tijuana$/i]: `America/Tijuana`,
    [/^(america\/)?toronto$/i]: `America/Toronto`,
    [/^(america\/)?vancouver$/i]: `America/Vancouver`,
    [/^(america\/)?whitehorse$/i]: `America/Whitehorse`,
    [/^(america\/)?winnipeg$/i]: `America/Winnipeg`,
    [/^(america\/)?yakutat$/i]: `America/Yakutat`,
    [/^(america\/)?godthab$/i]: `America/Nuuk`,
    [/^(america\/)?buenos(_| )?aires$/i]: `America/Argentina/Buenos_Aires`,
    [/^(america\/)?catamarca$/i]: `America/Argentina/Catamarca`,
    [/^(america\/)?cordoba$/i]: `America/Argentina/Cordoba`,
    [/^(america\/)?jujuy$/i]: `America/Argentina/Jujuy`,
    [/^(america\/)?mendoza$/i]: `America/Argentina/Mendoza`,
    [/^(america\/)?porto(_| )?acre$/i]: `America/Rio_Branco`,
    [/^(america\/)?kralendijk$/i]: `America/Puerto_Rico`,
    [/^(america\/)?lower(_| )?princes$/i]: `America/Puerto_Rico`,
    [/^(america\/)?marigot$/i]: `America/Puerto_Rico`,
    [/^(america\/)?st(_| )?barthelemy$/i]: `America/Puerto_Rico`,
    [/^(america\/)?virgin$/i]: `America/Puerto_Rico`,
    [/^(america\/)?knox(_| )?in$/i]: `America/Indiana/Knox`,
    [/^(america\/)?fort(_| )?wayne$/i]: `America/Indiana/Indianapolis`,
    [/^(america\/)?indianapolis$/i]: `America/Indiana/Indianapolis`,
    [/^(america\/)?louisville$/i]: `America/Kentucky/Louisville`,
    [/^(america\/)?atka$/i]: `America/Adak`,
    [/^(america\/)?shiprock$/i]: `America/Denver`,
    [/^(america\/)?santa(_| )?isabel$/i]: `America/Tijuana`,
    [/^(america\/)?(argentina\/)?comodrivadavia$/i]: `America/Argentina/Catamarca`,
    [/^(america\/)?rosario$/i]: `America/Argentina/Cordoba`,
    [/^(america\/)?anguilla$/i]: `America/Puerto_Rico`,
    [/^(america\/)?antigua$/i]: `America/Puerto_Rico`,
    [/^(america\/)?aruba$/i]: `America/Puerto_Rico`,
    [/^(america\/)?blanc-?sablon$/i]: `America/Puerto_Rico`,
    [/^(america\/)?curacao$/i]: `America/Puerto_Rico`,
    [/^(america\/)?dominica$/i]: `America/Puerto_Rico`,
    [/^(america\/)?grenada$/i]: `America/Puerto_Rico`,
    [/^(america\/)?guadeloupe$/i]: `America/Puerto_Rico`,
    [/^(america\/)?montserrat$/i]: `America/Puerto_Rico`,
    [/^(america\/)?port(_| )?of(_| )?spain$/i]: `America/Puerto_Rico`,
    [/^(america\/)?st(_| )?kitts$/i]: `America/Puerto_Rico`,
    [/^(america\/)?st(_| )?lucia$/i]: `America/Puerto_Rico`,
    [/^(america\/)?st(_| )?thomas$/i]: `America/Puerto_Rico`,
    [/^(america\/)?st(_| )?vincent$/i]: `America/Puerto_Rico`,
    [/^(america\/)?tortola$/i]: `America/Puerto_Rico`,
    [/^(america\/)?rainy(_| )?river$/i]: `America/Winnipeg`,
    [/^(america\/)?atikokan$/i]: `America/Panama`,
    [/^(america\/)?cayman$/i]: `America/Panama`,
    [/^(america\/)?coral(_| )?harbour$/i]: `America/Panama`,
    [/^(america\/)?montreal$/i]: `America/Toronto`,
    [/^(america\/)?nassau$/i]: `America/Toronto`,
    [/^(america\/)?nipigon$/i]: `America/Toronto`,
    [/^(america\/)?pangnirtung$/i]: `America/Iqaluit`,
    [/^(america\/)?thunder(_| )?bay$/i]: `America/Toronto`,
    [/^(america\/)?creston$/i]: `America/Phoenix`,
    [/^(america\/)?yellowknife$/i]: `America/Edmonton`,
    [/^(america\/)?ensenada$/i]: `America/Tijuana`,
    [/^(antarctica\/)?casey$/i]: `Antarctica/Casey`,
    [/^(antarctica\/)?davis$/i]: `Antarctica/Davis`,
    [/^(antarctica\/)?macquarie$/i]: `Antarctica/Macquarie`,
    [/^(antarctica\/)?mawson$/i]: `Antarctica/Mawson`,
    [/^(antarctica\/)?palmer$/i]: `Antarctica/Palmer`,
    [/^(antarctica\/)?rothera$/i]: `Antarctica/Rothera`,
    [/^(antarctica\/)?troll$/i]: `Antarctica/Troll`,
    [/^(antarctica\/)?vostok$/i]: `Antarctica/Vostok`,
    [/^(antarctica\/)?syowa$/i]: `Asia/Riyadh`,
    [/^(antarctica\/)?south(_| )?pole$/i]: `Pacific/Auckland`,
    [/^(antarctica\/)?dumontdurville$/i]: `Pacific/Port_Moresby`,
    [/^(antarctica\/)?mcmurdo$/i]: `Pacific/Auckland`,
    [/^iran$/i]: `Asia/Tehran`,
    [/^singapore$/i]: `Asia/Singapore`,
    [/^(asia\/)?istanbul$/i]: `Europe/Istanbul`,
    [/^(asia\/)?ashkhabad$/i]: `Asia/Ashgabat`,
    [/^(asia\/)?dacca$/i]: `Asia/Dhaka`,
    [/^(asia\/)?thimbu$/i]: `Asia/Thimphu`,
    [/^(asia\/)?saigon$/i]: `Asia/Ho_Chi_Minh`,
    [/^(asia\/)?ulan(_| )?bator$/i]: `Asia/Ulaanbaatar`,
    [/^(asia\/)?katmandu$/i]: `Asia/Kathmandu`,
    [/^(asia\/)?rangoon$/i]: `Asia/Yangon`,
    [/^(asia\/)?chungking$/i]: `Asia/Shanghai`,
    [/^(asia\/)?macao$/i]: `Asia/Macau`,
    [/^(asia\/)?calcutta$/i]: `Asia/Kolkata`,
    [/^(asia\/)?ujung(_| )?pandang$/i]: `Asia/Makassar`,
    [/^(asia\/)?aden$/i]: `Asia/Riyadh`,
    [/^(asia\/)?bahrain$/i]: `Asia/Qatar`,
    [/^(asia\/)?kuwait$/i]: `Asia/Riyadh`,
    [/^(asia\/)?muscat$/i]: `Asia/Dubai`,
    [/^(asia\/)?kashgar$/i]: `Asia/Urumqi`,
    [/^(asia\/)?phnom(_| )?penh$/i]: `Asia/Bangkok`,
    [/^(asia\/)?vientiane$/i]: `Asia/Bangkok`,
    [/^(asia\/)?brunei$/i]: `Asia/Kuching`,
    [/^(asia\/)?kuala(_| )?lumpur$/i]: `Asia/Singapore`,
    [/^(asia\/)?chongqing$/i]: `Asia/Shanghai`,
    [/^(asia\/)?harbin$/i]: `Asia/Shanghai`,
    [/^(asia\/)?tel(_| )?aviv$/i]: `Asia/Jerusalem`,
    [/^(asia\/)?almaty$/i]: `Asia/Almaty`,
    [/^(asia\/)?amman$/i]: `Asia/Amman`,
    [/^(asia\/)?anadyr$/i]: `Asia/Anadyr`,
    [/^(asia\/)?aqtau$/i]: `Asia/Aqtau`,
    [/^(asia\/)?aqtobe$/i]: `Asia/Aqtobe`,
    [/^(asia\/)?ashgabat$/i]: `Asia/Ashgabat`,
    [/^(asia\/)?atyrau$/i]: `Asia/Atyrau`,
    [/^(asia\/)?baghdad$/i]: `Asia/Baghdad`,
    [/^(asia\/)?baku$/i]: `Asia/Baku`,
    [/^(asia\/)?bangkok$/i]: `Asia/Bangkok`,
    [/^(asia\/)?barnaul$/i]: `Asia/Barnaul`,
    [/^(asia\/)?beirut$/i]: `Asia/Beirut`,
    [/^(asia\/)?bishkek$/i]: `Asia/Bishkek`,
    [/^(asia\/)?chita$/i]: `Asia/Chita`,
    [/^(asia\/)?choibalsan$/i]: `Asia/Choibalsan`,
    [/^(asia\/)?colombo$/i]: `Asia/Colombo`,
    [/^(asia\/)?damascus$/i]: `Asia/Damascus`,
    [/^(asia\/)?dhaka$/i]: `Asia/Dhaka`,
    [/^(asia\/)?dili$/i]: `Asia/Dili`,
    [/^(asia\/)?dubai$/i]: `Asia/Dubai`,
    [/^(asia\/)?dushanbe$/i]: `Asia/Dushanbe`,
    [/^(asia\/)?famagusta$/i]: `Asia/Famagusta`,
    [/^(asia\/)?gaza$/i]: `Asia/Gaza`,
    [/^(asia\/)?hebron$/i]: `Asia/Hebron`,
    [/^(asia\/)?ho(_| )?chi(_| )?minh$/i]: `Asia/Ho_Chi_Minh`,
    [/^(asia\/)?hong(_| )?kong$/i]: `Asia/Hong_Kong`,
    [/^(asia\/)?hovd$/i]: `Asia/Hovd`,
    [/^(asia\/)?irkutsk$/i]: `Asia/Irkutsk`,
    [/^(asia\/)?jakarta$/i]: `Asia/Jakarta`,
    [/^(asia\/)?jayapura$/i]: `Asia/Jayapura`,
    [/^(asia\/)?jerusalem$/i]: `Asia/Jerusalem`,
    [/^(asia\/)?kabul$/i]: `Asia/Kabul`,
    [/^(asia\/)?kamchatka$/i]: `Asia/Kamchatka`,
    [/^(asia\/)?karachi$/i]: `Asia/Karachi`,
    [/^(asia\/)?kathmandu$/i]: `Asia/Kathmandu`,
    [/^(asia\/)?khandyga$/i]: `Asia/Khandyga`,
    [/^(asia\/)?kolkata$/i]: `Asia/Kolkata`,
    [/^(asia\/)?krasnoyarsk$/i]: `Asia/Krasnoyarsk`,
    [/^(asia\/)?kuching$/i]: `Asia/Kuching`,
    [/^(asia\/)?macau$/i]: `Asia/Macau`,
    [/^(asia\/)?magadan$/i]: `Asia/Magadan`,
    [/^(asia\/)?makassar$/i]: `Asia/Makassar`,
    [/^(asia\/)?manila$/i]: `Asia/Manila`,
    [/^(asia\/)?nicosia$/i]: `Asia/Nicosia`,
    [/^(asia\/)?novokuznetsk$/i]: `Asia/Novokuznetsk`,
    [/^(asia\/)?novosibirsk$/i]: `Asia/Novosibirsk`,
    [/^(asia\/)?omsk$/i]: `Asia/Omsk`,
    [/^(asia\/)?oral$/i]: `Asia/Oral`,
    [/^(asia\/)?pontianak$/i]: `Asia/Pontianak`,
    [/^(asia\/)?pyongyang$/i]: `Asia/Pyongyang`,
    [/^(asia\/)?qatar$/i]: `Asia/Qatar`,
    [/^(asia\/)?qostanay$/i]: `Asia/Qostanay`,
    [/^(asia\/)?qyzylorda$/i]: `Asia/Qyzylorda`,
    [/^(asia\/)?riyadh$/i]: `Asia/Riyadh`,
    [/^(asia\/)?sakhalin$/i]: `Asia/Sakhalin`,
    [/^(asia\/)?samarkand$/i]: `Asia/Samarkand`,
    [/^(asia\/)?seoul$/i]: `Asia/Seoul`,
    [/^(asia\/)?shanghai$/i]: `Asia/Shanghai`,
    [/^(asia\/)?singapore$/i]: `Asia/Singapore`,
    [/^(asia\/)?srednekolymsk$/i]: `Asia/Srednekolymsk`,
    [/^(asia\/)?taipei$/i]: `Asia/Taipei`,
    [/^(asia\/)?tashkent$/i]: `Asia/Tashkent`,
    [/^(asia\/)?tbilisi$/i]: `Asia/Tbilisi`,
    [/^(asia\/)?tehran$/i]: `Asia/Tehran`,
    [/^(asia\/)?thimphu$/i]: `Asia/Thimphu`,
    [/^(asia\/)?tokyo$/i]: `Asia/Tokyo`,
    [/^(asia\/)?tomsk$/i]: `Asia/Tomsk`,
    [/^(asia\/)?ulaanbaatar$/i]: `Asia/Ulaanbaatar`,
    [/^(asia\/)?urumqi$/i]: `Asia/Urumqi`,
    [/^(asia\/)?ust-nera$/i]: `Asia/Ust-Nera`,
    [/^(asia\/)?vladivostok$/i]: `Asia/Vladivostok`,
    [/^(asia\/)?yakutsk$/i]: `Asia/Yakutsk`,
    [/^(asia\/)?yangon$/i]: `Asia/Yangon`,
    [/^(asia\/)?yekaterinburg$/i]: `Asia/Yekaterinburg`,
    [/^(asia\/)?yerevan$/i]: `Asia/Yerevan`,
    [/^(atlantic\/)?azores$/i]: `Atlantic/Azores`,
    [/^(atlantic\/)?bermuda$/i]: `Atlantic/Bermuda`,
    [/^(atlantic\/)?canary$/i]: `Atlantic/Canary`,
    [/^(atlantic\/)?cape(_| )?verde$/i]: `Atlantic/Cape_Verde`,
    [/^(atlantic\/)?faroe$/i]: `Atlantic/Faroe`,
    [/^(atlantic\/)?madeira$/i]: `Atlantic/Madeira`,
    [/^(atlantic\/)?south(_| )?georgia$/i]: `Atlantic/South_Georgia`,
    [/^(atlantic\/)?stanley$/i]: `Atlantic/Stanley`,
    [/^(atlantic\/)?jan(_| )?mayen$/i]: `Europe/Berlin`,
    [/^(atlantic\/)?reykjavik$/i]: `Africa/Abidjan`,
    [/^(atlantic\/)?st(_| )?helena$/i]: `Africa/Abidjan`,
    [/^(atlantic\/)?faeroe$/i]: `Atlantic/Faroe`,
    [/^(australia\/)?adelaide$/i]: `Australia/Adelaide`,
    [/^(australia\/)?brisbane$/i]: `Australia/Brisbane`,
    [/^(australia\/)?broken(_| )?hill$/i]: `Australia/Broken_Hill`,
    [/^(australia\/)?darwin$/i]: `Australia/Darwin`,
    [/^(australia\/)?eucla$/i]: `Australia/Eucla`,
    [/^(australia\/)?hobart$/i]: `Australia/Hobart`,
    [/^(australia\/)?lindeman$/i]: `Australia/Lindeman`,
    [/^(australia\/)?lord(_| )?howe$/i]: `Australia/Lord_Howe`,
    [/^(australia\/)?melbourne$/i]: `Australia/Melbourne`,
    [/^(australia\/)?perth$/i]: `Australia/Perth`,
    [/^(australia\/)?sydney$/i]: `Australia/Sydney`,
    [/^(australia\/)?lhi$/i]: `Australia/Lord_Howe`,
    [/^(australia\/)?north$/i]: `Australia/Darwin`,
    [/^(australia\/)?south$/i]: `Australia/Adelaide`,
    [/^(australia\/)?yancowinna$/i]: `Australia/Broken_Hill`,
    [/^(australia\/)?act$/i]: `Australia/Sydney`,
    [/^(australia\/)?canberra$/i]: `Australia/Sydney`,
    [/^(australia\/)?nsw$/i]: `Australia/Sydney`,
    [/^(australia\/)?queensland$/i]: `Australia/Brisbane`,
    [/^(australia\/)?tasmania$/i]: `Australia/Hobart`,
    [/^(australia\/)?victoria$/i]: `Australia/Melbourne`,
    [/^(australia\/)?west$/i]: `Australia/Perth`,
    [/^(australia\/)?currie$/i]: `Australia/Hobart`,
    [/^cet$/i]: `CET`,
    [/^cst6cdt$/i]: `CST6CDT`,
    [/^eet$/i]: `EET`,
    [/^est$/i]: `EST`,
    [/^est5edt$/i]: `EST5EDT`,
    [/^(etc\/)?gmt$/i]: `Etc/GMT`,
    [/^(etc\/)?gmt-1$/i]: `Etc/GMT-1`,
    [/^(etc\/)?gmt-2$/i]: `Etc/GMT-2`,
    [/^(etc\/)?gmt-3$/i]: `Etc/GMT-3`,
    [/^(etc\/)?gmt-4$/i]: `Etc/GMT-4`,
    [/^(etc\/)?gmt-5$/i]: `Etc/GMT-5`,
    [/^(etc\/)?gmt-6$/i]: `Etc/GMT-6`,
    [/^(etc\/)?gmt-7$/i]: `Etc/GMT-7`,
    [/^(etc\/)?gmt-8$/i]: `Etc/GMT-8`,
    [/^(etc\/)?gmt-9$/i]: `Etc/GMT-9`,
    [/^(etc\/)?gmt-10$/i]: `Etc/GMT-10`,
    [/^(etc\/)?gmt-11$/i]: `Etc/GMT-11`,
    [/^(etc\/)?gmt-12$/i]: `Etc/GMT-12`,
    [/^(etc\/)?gmt-13$/i]: `Etc/GMT-13`,
    [/^(etc\/)?gmt-14$/i]: `Etc/GMT-14`,
    [/^(etc\/)?gmt\+1$/i]: `Etc/GMT+1`,
    [/^(etc\/)?gmt\+2$/i]: `Etc/GMT+2`,
    [/^(etc\/)?gmt\+3$/i]: `Etc/GMT+3`,
    [/^(etc\/)?gmt\+4$/i]: `Etc/GMT+4`,
    [/^(etc\/)?gmt\+5$/i]: `Etc/GMT+5`,
    [/^(etc\/)?gmt\+6$/i]: `Etc/GMT+6`,
    [/^(etc\/)?gmt\+7$/i]: `Etc/GMT+7`,
    [/^(etc\/)?gmt\+8$/i]: `Etc/GMT+8`,
    [/^(etc\/)?gmt\+9$/i]: `Etc/GMT+9`,
    [/^(etc\/)?gmt\+10$/i]: `Etc/GMT+10`,
    [/^(etc\/)?gmt\+11$/i]: `Etc/GMT+11`,
    [/^(etc\/)?gmt\+12$/i]: `Etc/GMT+12`,
    [/^(etc\/)?utc$/i]: `Etc/UTC`,
    [/^(etc\/)?uct$/i]: `Etc/UCT`,
    [/^(etc\/)?gmt\+0$/i]: `Etc/GMT`,
    [/^(etc\/)?gmt-0$/i]: `Etc/GMT`,
    [/^(etc\/)?gmt0$/i]: `Etc/GMT`,
    [/^(etc\/)?greenwich$/i]: `Etc/GMT`,
    [/^(etc\/)?uct$/i]: `Etc/UTC`,
    [/^(etc\/)?universal$/i]: `Etc/UTC`,
    [/^(etc\/)?zulu$/i]: `Etc/UTC`,
    [/^gmt$/i]: `Etc/GMT`,
    [/^gmt\+0$/i]: `Etc/GMT`,
    [/^gmt-0$/i]: `Etc/GMT`,
    [/^gmt0$/i]: `Etc/GMT`,
    [/^greenwich$/i]: `Etc/GMT`,
    [/^uct$/i]: `Etc/UTC`,
    [/^universal$/i]: `Etc/UTC`,
    [/^utc$/i]: `Etc/UTC`,
    [/^zulu$/i]: `Etc/UTC`,
    [/^(europe\/)?andorra$/i]: `Europe/Andorra`,
    [/^(europe\/)?astrakhan$/i]: `Europe/Astrakhan`,
    [/^(europe\/)?athens$/i]: `Europe/Athens`,
    [/^(europe\/)?belgrade$/i]: `Europe/Belgrade`,
    [/^(europe\/)?berlin$/i]: `Europe/Berlin`,
    [/^(europe\/)?brussels$/i]: `Europe/Brussels`,
    [/^(europe\/)?bucharest$/i]: `Europe/Bucharest`,
    [/^(europe\/)?budapest$/i]: `Europe/Budapest`,
    [/^(europe\/)?chisinau$/i]: `Europe/Chisinau`,
    [/^(europe\/)?dublin$/i]: `Europe/Dublin`,
    [/^(europe\/)?gibraltar$/i]: `Europe/Gibraltar`,
    [/^(europe\/)?helsinki$/i]: `Europe/Helsinki`,
    [/^(europe\/)?istanbul$/i]: `Europe/Istanbul`,
    [/^(europe\/)?kaliningrad$/i]: `Europe/Kaliningrad`,
    [/^(europe\/)?kirov$/i]: `Europe/Kirov`,
    [/^(europe\/)?kyiv$/i]: `Europe/Kyiv`,
    [/^(europe\/)?lisbon$/i]: `Europe/Lisbon`,
    [/^(europe\/)?london$/i]: `Europe/London`,
    [/^(europe\/)?madrid$/i]: `Europe/Madrid`,
    [/^(europe\/)?malta$/i]: `Europe/Malta`,
    [/^(europe\/)?minsk$/i]: `Europe/Minsk`,
    [/^(europe\/)?moscow$/i]: `Europe/Moscow`,
    [/^(europe\/)?paris$/i]: `Europe/Paris`,
    [/^(europe\/)?prague$/i]: `Europe/Prague`,
    [/^(europe\/)?riga$/i]: `Europe/Riga`,
    [/^(europe\/)?rome$/i]: `Europe/Rome`,
    [/^(europe\/)?samara$/i]: `Europe/Samara`,
    [/^(europe\/)?saratov$/i]: `Europe/Saratov`,
    [/^(europe\/)?simferopol$/i]: `Europe/Simferopol`,
    [/^(europe\/)?sofia$/i]: `Europe/Sofia`,
    [/^(europe\/)?tallinn$/i]: `Europe/Tallinn`,
    [/^(europe\/)?tirane$/i]: `Europe/Tirane`,
    [/^(europe\/)?ulyanovsk$/i]: `Europe/Ulyanovsk`,
    [/^(europe\/)?vienna$/i]: `Europe/Vienna`,
    [/^(europe\/)?vilnius$/i]: `Europe/Vilnius`,
    [/^(europe\/)?volgograd$/i]: `Europe/Volgograd`,
    [/^(europe\/)?warsaw$/i]: `Europe/Warsaw`,
    [/^(europe\/)?zurich$/i]: `Europe/Zurich`,
    [/^(europe\/)?bratislava$/i]: `Europe/Prague`,
    [/^(europe\/)?busingen$/i]: `Europe/Zurich`,
    [/^(europe\/)?podgorica$/i]: `Europe/Belgrade`,
    [/^(europe\/)?san(_| )?marino$/i]: `Europe/Rome`,
    [/^(europe\/)?vatican$/i]: `Europe/Rome`,
    [/^(europe\/)?kiev$/i]: `Europe/Kyiv`,
    [/^(europe\/)?mariehamn$/i]: `Europe/Helsinki`,
    [/^(europe\/)?nicosia$/i]: `Asia/Nicosia`,
    [/^(europe\/)?amsterdam$/i]: `Europe/Brussels`,
    [/^(europe\/)?copenhagen$/i]: `Europe/Berlin`,
    [/^(europe\/)?ljubljana$/i]: `Europe/Belgrade`,
    [/^(europe\/)?luxembourg$/i]: `Europe/Brussels`,
    [/^(europe\/)?monaco$/i]: `Europe/Paris`,
    [/^(europe\/)?oslo$/i]: `Europe/Berlin`,
    [/^(europe\/)?sarajevo$/i]: `Europe/Belgrade`,
    [/^(europe\/)?skopje$/i]: `Europe/Belgrade`,
    [/^(europe\/)?stockholm$/i]: `Europe/Berlin`,
    [/^(europe\/)?vaduz$/i]: `Europe/Zurich`,
    [/^(europe\/)?zagreb$/i]: `Europe/Belgrade`,
    [/^(europe\/)?tiraspol$/i]: `Europe/Chisinau`,
    [/^(europe\/)?uzhgorod$/i]: `Europe/Kyiv`,
    [/^(europe\/)?zaporozhye$/i]: `Europe/Kyiv`,
    [/^(europe\/)?belfast$/i]: `Europe/London`,
    [/^(europe\/)?guernsey$/i]: `Europe/London`,
    [/^(europe\/)?isle(_| )?of(_| )?man$/i]: `Europe/London`,
    [/^(europe\/)?jersey$/i]: `Europe/London`,
    [/^(indian\/)?chagos$/i]: `Indian/Chagos`,
    [/^(indian\/)?maldives$/i]: `Indian/Maldives`,
    [/^(indian\/)?mauritius$/i]: `Indian/Mauritius`,
    [/^(indian\/)?mahe$/i]: `Asia/Dubai`,
    [/^(indian\/)?reunion$/i]: `Asia/Dubai`,
    [/^(indian\/)?kerguelen$/i]: `Indian/Maldives`,
    [/^(indian\/)?christmas$/i]: `Asia/Bangkok`,
    [/^(indian\/)?cocos$/i]: `Asia/Yangon`,
    [/^(indian\/)?antananarivo$/i]: `Africa/Nairobi`,
    [/^(indian\/)?comoro$/i]: `Africa/Nairobi`,
    [/^(indian\/)?mayotte$/i]: `Africa/Nairobi`,
    [/^(pacific\/)?apia$/i]: `Pacific/Apia`,
    [/^(pacific\/)?auckland$/i]: `Pacific/Auckland`,
    [/^(pacific\/)?bougainville$/i]: `Pacific/Bougainville`,
    [/^(pacific\/)?chatham$/i]: `Pacific/Chatham`,
    [/^(pacific\/)?easter$/i]: `Pacific/Easter`,
    [/^(pacific\/)?efate$/i]: `Pacific/Efate`,
    [/^(pacific\/)?fakaofo$/i]: `Pacific/Fakaofo`,
    [/^(pacific\/)?fiji$/i]: `Pacific/Fiji`,
    [/^(pacific\/)?galapagos$/i]: `Pacific/Galapagos`,
    [/^(pacific\/)?gambier$/i]: `Pacific/Gambier`,
    [/^(pacific\/)?guadalcanal$/i]: `Pacific/Guadalcanal`,
    [/^(pacific\/)?guam$/i]: `Pacific/Guam`,
    [/^(pacific\/)?honolulu$/i]: `Pacific/Honolulu`,
    [/^(pacific\/)?kanton$/i]: `Pacific/Kanton`,
    [/^(pacific\/)?kiritimati$/i]: `Pacific/Kiritimati`,
    [/^(pacific\/)?kosrae$/i]: `Pacific/Kosrae`,
    [/^(pacific\/)?kwajalein$/i]: `Pacific/Kwajalein`,
    [/^(pacific\/)?marquesas$/i]: `Pacific/Marquesas`,
    [/^(pacific\/)?nauru$/i]: `Pacific/Nauru`,
    [/^(pacific\/)?niue$/i]: `Pacific/Niue`,
    [/^(pacific\/)?norfolk$/i]: `Pacific/Norfolk`,
    [/^(pacific\/)?noumea$/i]: `Pacific/Noumea`,
    [/^(pacific\/)?pago(_| )?pago$/i]: `Pacific/Pago_Pago`,
    [/^(pacific\/)?palau$/i]: `Pacific/Palau`,
    [/^(pacific\/)?pitcairn$/i]: `Pacific/Pitcairn`,
    [/^(pacific\/)?port(_| )?moresby$/i]: `Pacific/Port_Moresby`,
    [/^(pacific\/)?rarotonga$/i]: `Pacific/Rarotonga`,
    [/^(pacific\/)?tahiti$/i]: `Pacific/Tahiti`,
    [/^(pacific\/)?tarawa$/i]: `Pacific/Tarawa`,
    [/^(pacific\/)?tongatapu$/i]: `Pacific/Tongatapu`,
    [/^(pacific\/)?samoa$/i]: `Pacific/Pago_Pago`,
    [/^(pacific\/)?chuuk$/i]: `Pacific/Port_Moresby`,
    [/^(pacific\/)?pohnpei$/i]: `Pacific/Guadalcanal`,
    [/^(pacific\/)?funafuti$/i]: `Pacific/Tarawa`,
    [/^(pacific\/)?majuro$/i]: `Pacific/Tarawa`,
    [/^(pacific\/)?wake$/i]: `Pacific/Tarawa`,
    [/^(pacific\/)?wallis$/i]: `Pacific/Tarawa`,
    [/^(pacific\/)?enderbury$/i]: `Pacific/Kanton`,
    [/^(pacific\/)?saipan$/i]: `Pacific/Guam`,
    [/^(pacific\/)?johnston$/i]: `Pacific/Honolulu`,
    [/^(pacific\/)?midway$/i]: `Pacific/Pago_Pago`,
    [/^(pacific\/)?truk$/i]: `Pacific/Port_Moresby`,
    [/^(pacific\/)?yap$/i]: `Pacific/Port_Moresby`,
    [/^(pacific\/)?ponape$/i]: `Pacific/Guadalcanal`,
    [/^(us\/)?alaska$/i]: `America/Anchorage`,
    [/^(us\/)?central$/i]: `America/Chicago`,
    [/^(us\/)?indiana-starke$/i]: `America/Indiana/Knox`,
    [/^(us\/)?east-indiana$/i]: `America/Indiana/Indianapolis`,
    [/^(us\/)?eastern$/i]: `America/New_York`,
    [/^(us\/)?michigan$/i]: `America/Detroit`,
    [/^(us\/)?aleutian$/i]: `America/Adak`,
    [/^(us\/)?hawaii$/i]: `Pacific/Honolulu`,
    [/^(us\/)?arizona$/i]: `America/Phoenix`,
    [/^(us\/)?mountain$/i]: `America/Denver`,
    [/^(us\/)?pacific$/i]: `America/Los_Angeles`,
    [/^(us\/)?samoa$/i]: `Pacific/Pago_Pago`,
    [/^(canada\/)?atlantic$/i]: `America/Halifax`,
    [/^(canada\/)?central$/i]: `America/Winnipeg`,
    [/^(canada\/)?saskatchewan$/i]: `America/Regina`,
    [/^(canada\/)?eastern$/i]: `America/Toronto`,
    [/^(canada\/)?mountain$/i]: `America/Edmonton`,
    [/^(canada\/)?yukon$/i]: `America/Whitehorse`,
    [/^(canada\/)?newfoundland$/i]: `America/St_Johns`,
    [/^(canada\/)?pacific$/i]: `America/Vancouver`,
    [/^(brazil\/)?denoronha$/i]: `America/Noronha`,
    [/^(brazil\/)?east$/i]: `America/Sao_Paulo`,
    [/^(brazil\/)?west$/i]: `America/Manaus`,
    [/^(brazil\/)?acre$/i]: `America/Rio_Branco`,
    [/^(chile\/)?continental$/i]: `America/Santiago`,
    [/^(chile\/)?easterisland$/i]: `Pacific/Easter`,
    [/^mexico(\/general)?$/i]: `America/Mexico_City`,
    [/^(mexico\/)?bajasur$/i]: `America/Mazatlan`,
    [/^(mexico\/)?bajanorte$/i]: `America/Tijuana`,
    [/^turkey$/i]: `Europe/Istanbul`,
    [/^(arctic\/)?longyearbyen$/i]: `Europe/Berlin`,
    [/^portugal$/i]: `Europe/Lisbon`,
    [/^poland$/i]: `Europe/Warsaw`,
    [/^gb$/i]: `Europe/London`,
    [/^gb-eire$/i]: `Europe/London`,
    [/^eire$/i]: `Europe/Dublin`,
    [/^w-su$/i]: `Europe/Moscow`,
    [/^kwajalein$/i]: `Pacific/Kwajalein`,
    [/^nz-chat$/i]: `Pacific/Chatham`,
    [/^cuba$/i]: `America/Havana`,
    [/^prc$/i]: `Asia/Shanghai`,
    [/^roc$/i]: `Asia/Taipei`,
    [/^egypt$/i]: `Africa/Cairo`,
    [/^libya$/i]: `Africa/Tripoli`,
    [/^jamaica$/i]: `America/Jamaica`,
    [/^iceland$/i]: `Africa/Abidjan`,
    [/^hongkong$/i]: `Asia/Hong_Kong`,
    [/^israel$/i]: `Asia/Jerusalem`,
    [/^japan$/i]: `Asia/Tokyo`,
    [/^rok$/i]: `Asia/Seoul`,
    [/^navajo$/i]: `America/Denver`,
    [/^nz$/i]: `Pacific/Auckland`,
    [/^factory$/i]: `Factory`,
    [/^pst8pdt$/i]: `PST8PDT`,
    [/^mst7mdt$/i]: `MST7MDT`,
    [/^wet$/i]: `WET`,
    [/^ast$/i]: `AST`,
    [/^cat$/i]: `CAT`,
    [/^cst$/i]: `CST`,
    [/^eat$/i]: `EAT`,
    [/^gmt$/i]: `GMT`,
    [/^bst$/i]: `BST`,
    [/^jst$/i]: `JST`,
    [/^nst$/i]: `NST`,
    [/^pst$/i]: `PST`,
    [/^sst$/i]: `SST`,
    [/^utc$/i]: `UTC`,
    [/^hst$/i]: `HST`,
    [/^met$/i]: `MET`,
    [/^mst$/i]: `MST`,
}

const validLocales = {
    [/^af-?za$/i]: `af-ZA`,
    [/^sq-?al$/i]: `sq-AL`,
    [/^ar-?dz$/i]: `ar-DZ`,
    [/^ar-?bh$/i]: `ar-BH`,
    [/^ar-?eg$/i]: `ar-EG`,
    [/^ar-?iq$/i]: `ar-IQ`,
    [/^ar-?jo$/i]: `ar-JO`,
    [/^ar-?kw$/i]: `ar-KW`,
    [/^ar-?lb$/i]: `ar-LB`,
    [/^ar-?ly$/i]: `ar-LY`,
    [/^ar-?ma$/i]: `ar-MA`,
    [/^ar-?om$/i]: `ar-OM`,
    [/^ar-?qa$/i]: `ar-QA`,
    [/^ar-?sa$/i]: `ar-SA`,
    [/^ar-?sy$/i]: `ar-SY`,
    [/^ar-?tn$/i]: `ar-TN`,
    [/^ar-?ae$/i]: `ar-AE`,
    [/^ar-?ye$/i]: `ar-YE`,
    [/^hy-?am$/i]: `hy-AM`,
    [/^az-?az$/i]: `az-AZ`,
    [/^eu-?es$/i]: `eu-ES`,
    [/^be-?by$/i]: `be-BY`,
    [/^bn-?in$/i]: `bn-IN`,
    [/^bs-?ba$/i]: `bs-BA`,
    [/^bg-?bg$/i]: `bg-BG`,
    [/^ca-?es$/i]: `ca-ES`,
    [/^zh-?cn$/i]: `zh-CN`,
    [/^zh-?hk$/i]: `zh-HK`,
    [/^zh-?mo$/i]: `zh-MO`,
    [/^zh-?sg$/i]: `zh-SG`,
    [/^zh-?tw$/i]: `zh-TW`,
    [/^hr-?hr$/i]: `hr-HR`,
    [/^cs-?cz$/i]: `cs-CZ`,
    [/^da-?dk$/i]: `da-DK`,
    [/^nl-?be$/i]: `nl-BE`,
    [/^nl-?nl$/i]: `nl-NL`,
    [/^en-?au$/i]: `en-AU`,
    [/^en-?bz$/i]: `en-BZ`,
    [/^en-?ca$/i]: `en-CA`,
    [/^en-?ie$/i]: `en-IE`,
    [/^en-?jm$/i]: `en-JM`,
    [/^en-?nz$/i]: `en-NZ`,
    [/^en-?ph$/i]: `en-PH`,
    [/^en-?za$/i]: `en-ZA`,
    [/^en-?tt$/i]: `en-TT`,
    [/^en-?vi$/i]: `en-VI`,
    [/^en-?gb$/i]: `en-GB`,
    [/^en-?us$/i]: `en-US`,
    [/^en-?zw$/i]: `en-ZW`,
    [/^et-?ee$/i]: `et-EE`,
    [/^fo-?fo$/i]: `fo-FO`,
    [/^fi-?fi$/i]: `fi-FI`,
    [/^fr-?be$/i]: `fr-BE`,
    [/^fr-?ca$/i]: `fr-CA`,
    [/^fr-?fr$/i]: `fr-FR`,
    [/^fr-?lu$/i]: `fr-LU`,
    [/^fr-?mc$/i]: `fr-MC`,
    [/^fr-?ch$/i]: `fr-CH`,
    [/^gl-?es$/i]: `gl-ES`,
    [/^ka-?ge$/i]: `ka-GE`,
    [/^de-?at$/i]: `de-AT`,
    [/^de-?de$/i]: `de-DE`,
    [/^de-?li$/i]: `de-LI`,
    [/^de-?lu$/i]: `de-LU`,
    [/^de-?ch$/i]: `de-CH`,
    [/^el-?gr$/i]: `el-GR`,
    [/^gu-?in$/i]: `gu-IN`,
    [/^he-?il$/i]: `he-IL`,
    [/^hi-?in$/i]: `hi-IN`,
    [/^hu-?hu$/i]: `hu-HU`,
    [/^is-?is$/i]: `is-IS`,
    [/^id-?id$/i]: `id-ID`,
    [/^it-?it$/i]: `it-IT`,
    [/^it-?ch$/i]: `it-CH`,
    [/^ja-?jp$/i]: `ja-JP`,
    [/^kn-?in$/i]: `kn-IN`,
    [/^kk-?kz$/i]: `kk-KZ`,
    [/^kok-?in$/i]: `kok-IN`,
    [/^ko-?kr$/i]: `ko-KR`,
    [/^lv-?lv$/i]: `lv-LV`,
    [/^lt-?lt$/i]: `lt-LT`,
    [/^mk-?mk$/i]: `mk-MK`,
    [/^ms-?bn$/i]: `ms-BN`,
    [/^ms-?my$/i]: `ms-MY`,
    [/^ml-?in$/i]: `ml-IN`,
    [/^mt-?mt$/i]: `mt-MT`,
    [/^mr-?in$/i]: `mr-IN`,
    [/^mn-?mn$/i]: `mn-MN`,
    [/^se-?no$/i]: `se-NO`,
    [/^nb-?no$/i]: `nb-NO`,
    [/^nn-?no$/i]: `nn-NO`,
    [/^fa-?ir$/i]: `fa-IR`,
    [/^pl-?pl$/i]: `pl-PL`,
    [/^pt-?br$/i]: `pt-BR`,
    [/^pt-?pt$/i]: `pt-PT`,
    [/^pa-?in$/i]: `pa-IN`,
    [/^ro-?ro$/i]: `ro-RO`,
    [/^ru-?ru$/i]: `ru-RU`,
    [/^sr-?ba$/i]: `sr-BA`,
    [/^sr-?cs$/i]: `sr-CS`,
    [/^sk-?sk$/i]: `sk-SK`,
    [/^sl-?si$/i]: `sl-SI`,
    [/^es-?ar$/i]: `es-AR`,
    [/^es-?bo$/i]: `es-BO`,
    [/^es-?cl$/i]: `es-CL`,
    [/^es-?co$/i]: `es-CO`,
    [/^es-?cr$/i]: `es-CR`,
    [/^es-?do$/i]: `es-DO`,
    [/^es-?ec$/i]: `es-EC`,
    [/^es-?sv$/i]: `es-SV`,
    [/^es-?gt$/i]: `es-GT`,
    [/^es-?hn$/i]: `es-HN`,
    [/^es-?mx$/i]: `es-MX`,
    [/^es-?ni$/i]: `es-NI`,
    [/^es-?pa$/i]: `es-PA`,
    [/^es-?py$/i]: `es-PY`,
    [/^es-?pe$/i]: `es-PE`,
    [/^es-?pr$/i]: `es-PR`,
    [/^es-?es$/i]: `es-ES`,
    [/^es-?uy$/i]: `es-UY`,
    [/^es-?ve$/i]: `es-VE`,
    [/^sw-?ke$/i]: `sw-KE`,
    [/^sv-?fi$/i]: `sv-FI`,
    [/^sv-?se$/i]: `sv-SE`,
    [/^syr-?sy$/i]: `syr-SY`,
    [/^ta-?in$/i]: `ta-IN`,
    [/^te-?in$/i]: `te-IN`,
    [/^th-?th$/i]: `th-TH`,
    [/^tn-?za$/i]: `tn-ZA`,
    [/^tr-?tr$/i]: `tr-TR`,
    [/^uk-?ua$/i]: `uk-UA`,
    [/^uz-?uz$/i]: `uz-UZ`,
    [/^vi-?vn$/i]: `vi-VN`,
    [/^cy-?gb$/i]: `cy-GB`,
    [/^xh-?za$/i]: `xh-ZA`,
    [/^zu-?za$/i]: `zu-ZA`,
}

function validateTimeZone(str) {
    logMessage([`> validateTimeZone(str: ${str})`])
    for (const timeZone of Object.keys(validTimeZones)) {
        const regex = new RegExp(timeZone.split(`/`).slice(1, timeZone.split(`/`).length - 1).join(`/`), timeZone.split(`/`)[timeZone.split(`/`).length - 1])
        if (regex.test(str)) {
            return validTimeZones[regex]
        }
    }
    logMessage([`-> Timezone "${str}" not found, falling back on ${settings.timeZone}`])
    return settings.timeZone
}

function validateTimeLocale(str) {
    logMessage([`> validateTimeLocale(str: ${str})`])
    for (const locale of Object.keys(validLocales)) {
        const regex = new RegExp(locale.split(`/`).slice(1, locale.split(`/`).length - 1).join(`/`), locale.split(`/`)[locale.split(`/`).length - 1])
        if (regex.test(str)) {
            return validLocales[regex]
        }
    }
    logMessage([`-> Locale "${str}" not found, falling back on ${settings.timeLocale}`])
    return settings.timeLocale
}

module.exports = {
    validTimeZones,
    validLocales,
    getTime(props) {
        const { bot, chatroom, args, currentTime } = props
        logMessage([`> getTime(chatroom: ${chatroom}, tz: ${args[0]}, locale: ${args[1]})`])

        const tz = validateTimeZone(args[0])
        const locale = validateTimeLocale(args[1])

        const date = new Date(currentTime).toLocaleDateString(locale, { weekday: `short`, year: `numeric`, month: `short`, day: `numeric`, timeZone: tz })
        const time = new Date(currentTime).toLocaleTimeString(locale, { timeZone: tz })

        const neutralEmote = getContextEmote(`neutral`, chatroom.substring(1))
        bot.say(chatroom, `The current time is ${time} ${tz} on ${date}! ${neutralEmote}`)
    }
}
